### ISSUE TITLE
Traceback if curly braces in config file

### ISSUE THREAD

**Issue by sebw** [fiskhest/sxhkd-helper-menu#2]
Thanks for this helper menu, exactly what I was looking for.

I had this config where the $id var was between curly braces

```
# Move and follow window to desktop until 11
ctrl + super + shift + {1-9,0,minus}
    id=$(bspc query -N -n); bspc node -d ^{1-9,0,11}; bspc node -f ${id}
```
This breaks hkhelper.py:

```
Traceback (most recent call last):
  File "/home/s/tmp/hkhelper.py", line 285, in <module>
    main()
  File "/home/s/tmp/hkhelper.py", line 267, in main
    config = sxhkd_helper(args.file, args.descriptor, args.category_descriptor)
  File "/home/s/tmp/hkhelper.py", line 22, in __init__
    self.keybinds = self._get_keybinds()
  File "/home/s/tmp/hkhelper.py", line 38, in _get_keybinds
    for parsed_keybind in self._parse_keybinds():
  File "/home/s/tmp/hkhelper.py", line 77, in _parse_keybinds
    unchained_lines = self._unchain_lines(lines)
  File "/home/s/tmp/hkhelper.py", line 110, in _unchain_lines
    return_lines.append(self._unchain(chain.group(0), line, index))
  File "/home/s/tmp/hkhelper.py", line 147, in _unchain
    end_of_range = int(re.sub(r',.*', '', copy_keys[-1]))
ValueError: invalid literal for int() with base 10: 'f ${id'
```

I just removed the curlies from my config as a workaround.

**Comment by fiskhest** [comment]
Hey sebw and thank you for the detailed report :slightly_smiling_face: 

In sxhkd configuration curly braces are used for nominating expansions. It seems I took a shortcut and only ever expected a pair of curly braces to expand, though your use case is valid and should be supported.

I was able to fix the traceback crash, but the expansions aren't done correctly yet:
```
❯ python hkhelper.py -f test.cfg
Move and follow window to desktop until 11  ctrl + super + shift + 1      id=$(bspc query -N -n); bspc node -d ^1
Move and follow window to desktop until 11  ctrl + super + shift + 2      id=$(bspc query -N -n); bspc node -d ^2
Move and follow window to desktop until 11  ctrl + super + shift + 3      id=$(bspc query -N -n); bspc node -d ^3
Move and follow window to desktop until 11  ctrl + super + shift + 4      id=$(bspc query -N -n); bspc node -d ^4
Move and follow window to desktop until 11  ctrl + super + shift + 5      id=$(bspc query -N -n); bspc node -d ^5
Move and follow window to desktop until 11  ctrl + super + shift + 6      id=$(bspc query -N -n); bspc node -d ^6
Move and follow window to desktop until 11  ctrl + super + shift + 7      id=$(bspc query -N -n); bspc node -d ^7
Move and follow window to desktop until 11  ctrl + super + shift + 8      id=$(bspc query -N -n); bspc node -d ^8
Move and follow window to desktop until 11  ctrl + super + shift + 9      id=$(bspc query -N -n); bspc node -d ^9
Move and follow window to desktop until 11  ctrl + super + shift + 0      id=$(bspc query -N -n); bspc node -d ^0
Move and follow window to desktop until 11  ctrl + super + shift + minus  id=$(bspc query -N -n); bspc node -d ^11}; bspc node -f ${id   <--- a } is missing, and all lines above this one should look the same
```

I should be able to come up with a solution though it's been a long time since I last touched this codebase, so it'll be a while before I can push a permanent fix.

**Comment by fiskhest** [comment]
@sebw I just pushed v0.3.6 that should address this issue. This marks the first issue reported by an external contributer ever solved for this project :fireworks: thank you!

As a small sidenote, did you know you can also expand the comment? :slightly_smiling_face: 

Something like:
```
# Move and follow window to desktop {1-11}
ctrl + super + shift + {1-9,0,minus}
    id=$(bspc query -N -n); bspc node -d ^{1-9,0,11}; bspc node -f ${id}
```

expands to:
```
Move and follow window to desktop 1   ctrl + super + shift + 1      id=$(bspc query -N -n); bspc node -d ^1; bspc node -f ${id}
Move and follow window to desktop 2   ctrl + super + shift + 2      id=$(bspc query -N -n); bspc node -d ^2; bspc node -f ${id}
Move and follow window to desktop 3   ctrl + super + shift + 3      id=$(bspc query -N -n); bspc node -d ^3; bspc node -f ${id}
Move and follow window to desktop 4   ctrl + super + shift + 4      id=$(bspc query -N -n); bspc node -d ^4; bspc node -f ${id}
Move and follow window to desktop 5   ctrl + super + shift + 5      id=$(bspc query -N -n); bspc node -d ^5; bspc node -f ${id}
Move and follow window to desktop 6   ctrl + super + shift + 6      id=$(bspc query -N -n); bspc node -d ^6; bspc node -f ${id}
Move and follow window to desktop 7   ctrl + super + shift + 7      id=$(bspc query -N -n); bspc node -d ^7; bspc node -f ${id}
Move and follow window to desktop 8   ctrl + super + shift + 8      id=$(bspc query -N -n); bspc node -d ^8; bspc node -f ${id}
Move and follow window to desktop 9   ctrl + super + shift + 9      id=$(bspc query -N -n); bspc node -d ^9; bspc node -f ${id}
Move and follow window to desktop 10  ctrl + super + shift + 0      id=$(bspc query -N -n); bspc node -d ^0; bspc node -f ${id}
Move and follow window to desktop 11  ctrl + super + shift + minus  id=$(bspc query -N -n); bspc node -d ^11; bspc node -f ${id}
```

**Comment by sebw** [comment]
Thanks for the quick fix @fiskhest 

Yeah I use the expansion :-) The only thing I haven't quite figured out yet is how to use the exec function, but didn't put much effort in it because I just moved from i3wm and need to practice my shortcuts :D
